  version: "3.8"

  services:

    db:
      container_name: db
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_USERNAME': 'root'
        MySQL_PASSWORD': 'rootadmin123'
        MYSQL_ROOT_PASSWORD: 'rootadmin123'
        MYSQL_DATABASE: 'fastapi'
      ports:
        - "3308:3308"


    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
        PMA_HOST: db
      ports:
        - "8080:80"


    app:
      container_name: app
      build: .
      entrypoint: bin/restart_server.sh
      environment:
        - SQLALCHEMY_DATABASE_URL=mysql://root:rootadmin123@db/fastapi
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      depends_on:
        - db
      restart: always


    rabbitmq:
      container_name: rabbitmq
      image: "rabbitmq:latest"
      environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
      expose:
        - 5672
        - 15672


    worker:
      build: .
      container_name: worker
      entrypoint: bin/restart_celery.sh
      links:
        - rabbitmq
      depends_on:
        - rabbitmq
      volumes:
        - .:/app
      restart: always


    beat:
      build: .
      container_name: beat
      entrypoint: bin/restart_beat.sh
      links:
        - rabbitmq
        - worker
      depends_on:
        - rabbitmq
        - worker
        - db
      volumes:
        - .:/app


