  version: "3.8"

  services:

    mysql:
      container_name: mysqldb
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: LhUMp6OwKVZVXoOD
        MYSQL_DATABASE: debian-sys-maint

    app:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - PORT=8000
        - SQLALCHEMY_DATABASE_URL=mysql://debian-sys-maint:LhUMp6OwKVZVXoOD@localhost/fastapi
      ports:
        - 8080:80
      depends_on:
        - mysql
      restart: always

